services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5555:5432" # optional: expose for local tools
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      # Hedef DB yoksa healthcheck geçmez; bu yüzden 'postgres' sistem DB'sine ping atıyoruz
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  pgdata:
