services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    env_file:
      - .env
    ports:
      - "3000:3000"

  db:
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d PlaygroundDb"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DB_SSL=false
    depends_on:
      db:
        condition: service_healthy
    command: ["bun", "run", "scripts/migrate.ts"]
    restart: "no"

volumes:
  postgres_data:
